export const TRY_REGISTER = 'TRY_REGISTER'
export const TRY_LOGIN = 'TRY_LOGIN'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION'
export const AUTH_TRUE = 'AUTH_TRUE'
export const AUTH_FALSE = 'AUTH_FALSE'
export const LOGOUT = 'LOGOUT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const SET_STOCK_PRICES = 'SET_STOCK_PRICES'
export const GET_WALLET_DATA = 'GET_WALLET_DATA'
export const SET_WALLET_DATA = 'SET_WALLET_DATA'

export const BUY_STOCK = 'BUY_STOCK'
export const SELL_STOCK = 'SELL_STOCK'

export const SAVE_USER_CHANGES = 'SAVE_USER_CHANGES'

export const DISPLAY_MESSAGE = 'DISPLAY_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const GET_PRICE_HISTORY = 'GET_PRICE_HISTORY'
export const SET_PRICE_HISTORY = 'SET_PRICE_HISTORY'